### ISSUE TITLE
Gulp failing -> AssertionError: missing path -> unsure of fix 

### ISSUE THREAD

**Issue by joshuazong** [google/web-starter-kit#655]
Hello,

All the files mentioned in the AssertionError exist at the locations marked on the below list (as far as I can tell).  Running on Mavericks. Web Starter Kit version 0.5.2

[13:58:08] Using gulpfile ~/webkit/gulpfile.js
[13:58:08] Starting 'clean'...
[13:58:08] Finished 'clean' after 7.47 ms
[13:58:08] Starting 'default'...
[13:58:08] Starting 'styles'...
[13:58:08] 'styles' errored after 14 ms
[13:58:08] AssertionError: missing path
    at Module.require (module.js:363:3)
    at require (module.js:384:17)
    at requireFn (/Users/Zong/webkit/node_modules/gulp-load-plugins/index.js:37:14)
    at Object.defineProperty.get (/Users/Zong/webkit/node_modules/gulp-load-plugins/index.js:68:18)
    at Gulp.<anonymous> (/Users/Zong/webkit/gulpfile.js:90:12)
    at module.exports (/Users/Zong/webkit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Zong/webkit/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Zong/webkit/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/Zong/webkit/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/Zong/webkit/node_modules/run-sequence/index.js:74:16)
[13:58:08] 'default' errored after 18 ms
[13:58:08] Error: [object Object]
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (/Users/Zong/webkit/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/Zong/webkit/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Zong/webkit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/Zong/webkit/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at finish (/Users/Zong/webkit/node_modules/run-sequence/index.js:48:5)
    at Gulp.onError (/Users/Zong/webkit/node_modules/run-sequence/index.js:55:4)
    at Gulp.emit (events.js:129:20)

Any suggestions of even where to look would be appreciated.  Or point me on a path of what to research to resolve the issue.  I can't seem to "I can Google that for me" with this particular issue. Maybe I will run into an answer, or at least a research rabbit hole.

Update; Currently looking  through 'npm faq', seems like I will be reading a lot.

Thanks for your time,
-Joshua

**Comment by joshuazong** [comment]
I only post this as

**Comment by ohyouknowwho** [comment]
@joshuazong

If you've only just started with it I would uninstall node completely. Reinstall to the latest node version 0.12.0. I would personally delete all your wsk files and redownload.

<code>$ cd Users/......./web-starter-kit-0.5.2</code>

<code>$ npm install</code>

<code>$ npm install gulp -g</code>

<code>
gulp serve </code>

That's how I solved my problems which were similar. You could delete the .sass-cache folder, .tmp folders. (Then if that doesn't work the dist folder) that might resolve it too.

This should work now. Let me know.

Thanks Tom

**Comment by joshuazong** [comment]
@ohyouknowwho 

Thanks for the advice!!!

I did a reinstall of node (which was v0.12.0 with folders in my MAMP setup) and deleted the .sass-cache as suggested.  Then went ahead and installed the required modules that were not a part of the install to the correct locations (postcss, caniuse-db, and pako this time, before it was a differing set of modules missing).  Now everything is working well.

Cheers,
-Joshua

**Comment by aastharawat** [comment]
v3 is deprecated. Here you are using the latest version but older code. 
With v4, 
replace  gulp.watch('./sass/*.sass', ['sass']) with gulp.watch('./sass/*.sass', gulp.series('sass')).
