### ISSUE TITLE
Error: Cannot find module 'browserslist'

### ISSUE THREAD

**Issue by jahoward11** [google/web-starter-kit#668]
I tried installing on Mac OS X Yosemite.

When I tried `gulp serve` in the project root directory, I got the following result:

~~~
[15:42:12] Using gulpfile ~/chromedev/wsk/gulpfile.js
[15:42:12] Starting 'styles'...
[15:42:17] 'styles' errored after 4.62 s
[15:42:17] Error: Cannot find module 'browserslist'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/username/chromedev/wsk/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/lib/autoprefixer.js:6:18)
    at Object.<anonymous> (/Users/username/chromedev/wsk/node_modules/gulp-autoprefixer/node_modules/autoprefixer-core/lib/autoprefixer.js:109:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
~~~

**Comment by sindresorhus** [comment]
Upgrade npm and reinstall. This is a common npm install corruption.
