### ISSUE TITLE
cb() never called

### ISSUE THREAD

**Issue by panchowtf** [google/web-starter-kit#669]
using `sudo npm install` everything goes ok bit suddenly i get 
```bash
`darwin-x64-node-0.10` exists; testing
Binary is fine; exiting
npm ERR! cb() never called!
```
and it errors out
I ignored this and used `gulp serve` two modules where missing so i installed them manualy but now using `gulp serve`i get 
```bash
10:09:55] Using gulpfile ~/Desktop/Sitios/bill/gulpfile.js
[10:09:55] Starting 'styles'...
[10:09:55] 'styles' errored after 80 ms
[10:09:55] TypeError: Object #<Object> has no method 'rubySass'
    at Gulp.gulp.task.$.useref.assets.searchPath (/Users/mercadotecnia/Desktop/Sitios/bill/gulpfile.js:91:13)
    at module.exports (/Users/mercadotecnia/Desktop/Sitios/bill/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mercadotecnia/Desktop/Sitios/bill/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mercadotecnia/Desktop/Sitios/bill/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mercadotecnia/Desktop/Sitios/bill/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
iMac-de-Mercadotecnia-3:bill mercadotecnia$ gulp serve
[10:10:31] Using gulpfile ~/Desktop/Sitios/bill/gulpfile.js
[10:10:31] Starting 'styles'...
[10:10:31] 'styles' errored after 76 ms
[10:10:31] TypeError: Object #<Object> has no method 'rubySass'
    at Gulp.gulp.task.$.useref.assets.searchPath (/Users/mercadotecnia/Desktop/Sitios/bill/gulpfile.js:91:13)
    at module.exports (/Users/mercadotecnia/Desktop/Sitios/bill/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mercadotecnia/Desktop/Sitios/bill/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mercadotecnia/Desktop/Sitios/bill/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mercadotecnia/Desktop/Sitios/bill/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by sindresorhus** [comment]
npm install errors has nothing to do with this project.

npm support here: https://github.com/npm/npm/issues
