### ISSUE TITLE
Gulp Serve Error

### ISSUE THREAD

**Issue by arecvlohe** [google/web-starter-kit#673]
I get this error when I run gulp serve on my root folder.

Error: Cannot find module 'googleapis'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Adam/Desktop/google-starter/node_modules/psi/index.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by sindresorhus** [comment]
You seem to have not run `npm install` or have suffered an npm install corruption. Upgrade to latest Node.js and npm (`$ npm install -g npm` and reinstall.

npm support: https://github.com/npm/npm/issues
