### ISSUE TITLE
node-sass installation

### ISSUE THREAD

**Issue by mvasin** [google/web-starter-kit#756]
I couldn't run 'npm install' without errors on 'gulp-sass' installation (and because of that 'gulp' stopped on error as well) until I changed gulp-sass version to "latest" in package.json. I know, 'latest' is not the best solution, but it worked for me.

**Comment by Xaviju** [comment]
Same here, worked using **latest**. 

```
'styles' errored after 65 ms
[19:55:25] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/***/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/***/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/***/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:434:26)
[19:55:25] 'default' errored after 71 ms
[19:55:25] Error in plugin 'run-sequence'
```
Removed path and replaced with ***

Tried many things reinstalling everything but keeps stopping.

**Comment by nockgeneer** [comment]
You need to download the actual latest: https://github.com/google/web-starter-kit/releases/tag/v0.6.0-rc.1

It's hidden because they didn't provide release notes.

**Comment by lodestarops** [comment]
Thanks @jpc-ae! This helps out a lot! 

Do you (or anyone) know when v0.6.0-rc* is going to be released officially? I'm hoping soon. I'd like to use a officially released version for production (I'm fine with RC1 for testing).

Thanks in advance!

**Comment by mvasin** [comment]
Maybe it's better to switch to gulp-ruby-sass, it installs and works like a charm.

**Comment by robwierzbowski** [comment]
GRS has its own set of issues, primarily speed. I'll swing over to gulp-sass and see if there's anything I can do to help get 6.0 released.

**Comment by lodestarops** [comment]
Closed #762 since it seems like the same issue.

**Comment by jpc-ae** [comment]
If anyone is wondering, it seems the relevant commits are here:
[1] https://github.com/google/web-starter-kit/commit/4e2141a9831aa69da1edc007ed02ac7f6ad5dbc5
[2] https://github.com/google/web-starter-kit/commit/4f382705f8cd2806a8872a8cded39fabdda666bf
[3] https://github.com/google/web-starter-kit/commit/d05b5ac4766c3a5f75ad0fb38ae615e14dc39d74

This one I don't think is related, but does affect the styles task as well:
https://github.com/google/web-starter-kit/commit/0b94f55fa3d21ef28df916672b63dac919c633d3

**Comment by addyosmani** [comment]
Hey folks. I haven't been able to repro this issue using https://github.com/google/web-starter-kit/releases/tag/v0.6.0-rc.4 on Windows or Mac. Can you try out that build and let me know if you're still seeing node-sass issues there? Our dependencies should be fairly up to date across the board right now.

0.6.0 release date: soon. I'm aiming to get it out next week pending some last remaining checks on bugs folks experienced with older versions..this being one of them :)

**Comment by lodestarops** [comment]
Wasn't able to reproduce on Mac Yosemite using v0.6.0-rc4. Awesome job!

On Thursday, November 26, 2015, Addy Osmani <notifications@github.com>
wrote:

> Hey folks. I haven't been able to repro this issue using
> https://github.com/google/web-starter-kit/releases/tag/v0.6.0-rc.4 on
> Windows or Mac. Can you try out that build and let me know if you're still
> seeing node-sass issues there? Our dependencies should be fairly up to date
> across the board right now.
>
> 0.6.0 release date: soon. I'm aiming to get it out next week pending some
> last remaining checks on bugs folks experienced with older versions..this
> being one of them :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/web-starter-kit/issues/756#issuecomment-159926275>
> .
>


-- 


__________________________________________

David Chen & The Lodestar Crew!

LODESTAR | lodestarcollective.com <http://www.lodestarcollective.com/>
949-232-8868 | dchen@lodestarcollective.com

**Comment by gauntface** [comment]
🐛 **Bankruptcy**: Closing due to inactivity.
