### ISSUE TITLE
gulp default command: Unhandled rejection TypeError: Cannot read property 'read' of undefined

### ISSUE THREAD

**Issue by postai** [google/web-starter-kit#761]
Node Version: v4.2.1
Gulp Version 3.9.0
NPM Version: 2.14.7
node -p process.versions
{ http_parser: '2.5.0',
  node: '4.2.1',
  v8: '4.5.103.35',
  uv: '1.7.5',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2d' }
node -p process.platform: win32
node -p process.arch: x64

C:\Users\postai\Downloads\casadeoracao>gulp
[16:53:57] Using gulpfile ~\Downloads\casadeoracao\gulpfile.js
[16:53:57] Starting 'clean'...
[16:53:57] Finished 'clean' after 27 ms
[16:53:57] Starting 'default'...
[16:53:57] Starting 'styles'...
[16:54:03] styles all files 92.98 kB
[16:54:03] Finished 'styles' after 5.22 s
[16:54:03] Starting 'jshint'...
[16:54:05] Starting 'html'...
[16:54:12] Starting 'images'...
[16:54:15] Starting 'fonts'...
[16:54:15] Starting 'copy'...
Unhandled rejection TypeError: Cannot read property 'read' of undefined
    at wrap (C:\project\node_modules\gulp-imagemin\node_modules\imagemin
\node_modules\stream-combiner2\index.js:66:16)
    at combine (C:\project\node_modules\gulp-imagemin\node_modules\image
min\node_modules\stream-combiner2\index.js:29:18)
    at Function.module.exports.obj (C:\project\node_modules\gulp-imagemi
n\node_modules\imagemin\node_modules\stream-combiner2\index.js:22:10)
    at Imagemin.createStream (C:\project\node_modules\gulp-imagemin\node
_modules\imagemin\index.js:104:24)
    at Imagemin.run (C:\project\node_modules\gulp-imagemin\node_modules\
imagemin\index.js:78:20)
    at DestroyableTransform.through.obj.percent (C:\project\node_modules
\gulp-imagemin\index.js:56:12)
    at DestroyableTransform._transform (C:\project\node_modules\gulp-ima
gemin\node_modules\through2-concurrent\through2-concurrent.js:29:15)
    at DestroyableTransform.Transform._read (C:\project\node_modules\gul
p-imagemin\node_modules\through2-concurrent\node_modules\through2\node_modules\readable-stream\lib\_
stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (C:\project\node_modules\gu
lp-imagemin\node_modules\through2-concurrent\node_modules\through2\node_modules\readable-stream\lib\
_stream_transform.js:160:12)
    at doWrite (C:\project\node_modules\gulp-imagemin\node_modules\throu
gh2-concurrent\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:326:12)
    at writeOrBuffer (C:\project\node_modules\gulp-imagemin\node_modules
\through2-concurrent\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:312:
5)
    at DestroyableTransform.Writable.write (C:\project\node_modules\gulp
-imagemin\node_modules\through2-concurrent\node_modules\through2\node_modules\readable-stream\lib\_s
tream_writable.js:239:11)
    at _.extend._runProxiedTask (C:\project\node_modules\gulp-cache\lib\
TaskProxy.js:154:19)
    at _.extend._runProxiedTaskAndCache (C:\project\node_modules\gulp-ca
che\lib\TaskProxy.js:105:21)
    at C:\project\node_modules\gulp-cache\lib\TaskProxy.js:26:25
    at tryCatcher (C:\project\node_modules\gulp-cache\node_modules\blueb
ird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\project\node_modules\gulp-c
ache\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\project\node_modules\gulp-cache\node
_modules\bluebird\js\main\promise.js:581:18)
    at Async._drainQueue (C:\project\node_modules\gulp-cache\node_module
s\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\project\node_modules\gulp-cache\node_modul
es\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\project\node_mo
dules\gulp-cache\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)

The "gulp serve" command work perfectly.

**Comment by addyosmani** [comment]
Is this using the version of Web Starter Kit from master or were you using a specific older version?

**Comment by sindresorhus** [comment]
Try reinstalling `gulp-imagemin`.

**Comment by addyosmani** [comment]
Testing WSK against Windows using master on a fresh install I haven't been able to reproduce these issues. As Sindre mentions above, it's worth trying to reinstall gulp-imagemin (I'd probably run `npm cache clean` and reinstall everything with `npm install` just to be on the safe side).

**Comment by sbley** [comment]
I ran into the same problem with Polymer Starter Kit. As it happens only when building on our Jenkins VM which does not have internet access I guess one of gulp-imagemin's dependencies is trying to access internet resources.
