### ISSUE TITLE
Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by lodestarops** [google/web-starter-kit#762]
Hi Guys,

I just recently updated to El Captain on Mac and it seems I'm having an issue installing the web-starter-kit-0.5.4, I was hoping someone could help me. Thanks in advance! I'm going to write this as a bug report hopefully this will help.

## Issue ##
After downloading web-starter-kit-0.5.4, I used 'brew' to update node.js to v4.2.1 and npm -v 2.14.7. 
After I navigate to the web-starter-kit-0.5.4 directory and ran:

*$ cd web-starter-kit-0.5.4*
*$ npm install*

First Warning (not sure what this means):
```console
> utf-8-validate@1.2.1 install /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/browser-sync/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
```

Things seem to install fine for a while, until I run into the gyp install. Here it seems like it can't install gyp, not quite sure how to fix this part, I did try a few things which I'll put in the _Additional Info_ section below so we can rule some stuff out:

```console
> node-sass@2.1.1 postinstall /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

gyp: /Users/oxymoron/.node-gyp/4.2.1/common.gypi not found (cwd: /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.2.1/bin/node" "/Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.2.1
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed
apache-server-configs@2.14.0 node_modules/apache-server-configs

opn@1.0.2 node_modules/opn

require-dir@0.1.0 node_modules/require-dir
```

I wasn't sure how an error on the gyp installation would affect the over all build, so I continued on to the next step...

*$ npm install gulp -g*
*$ gulp -v*
*[19:19:58] CLI version 3.9.0*
*[19:19:58] Local version 3.9.0*

Gulp seems to install fine... =)

Now let's see what happens once I run gulp!

*$ gulp*

```ShellSession
[19:20:40] Using gulpfile /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/gulpfile.js
[19:20:40] Starting 'clean'...
[19:20:40] Finished 'clean' after 5.95 ms
[19:20:40] Starting 'default'...
[19:20:40] Starting 'styles'...
[19:20:40] 'styles' errored after 229 ms
[19:20:40] Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:435:26)
[19:20:40] 'default' errored after 231 ms
[19:20:40] Error in plugin 'run-sequence'
Message:
    An error occured in task 'styles'.

```

Welp! That didn't work... My assumption is that gyp has some hooks into node-sass which didn't install correctly thus affecting libsass rendering the build to have no styles. 

Any ideas on what I could be doing wrong or how I can fix this?

## Additional Info ##

I'm currently running: 
*MBP Retina Late 2013*
*OSX El Captain Version 10.11*
*Command Line Tools Xcode7.0.1.(7A1001)*
*AMPPS v2.1*
*Homebrew 0.9.5 (git revision 5e80b7; last commit 2015-10-18)*
*NPM 2.14.7*
*Node v4.2.1*
*web-starter-kit-0.5.4*

Obviously I tried to troubleshoot myself (how else would I learn & return the favor?), but didn't come to a fix for the issue. So to help rule out what could be the issue here's what I tried: 

###Re-Installing NPM###
I tried deleting 'node_modules/' and reinstalling by running *$ npm install*. I also checked package.json which looks fine 

```json
{
  "devDependencies": {
    "apache-server-configs": "^2.7.1",
    "browser-sync": "^1.3.0",
    "del": "^1.1.0",
    "gulp": "^3.8.5",
    "gulp-autoprefixer": "^2.0.0",
    "gulp-cache": "0.2.2",
    "gulp-changed": "^1.0.0",
    "gulp-csso": "^1.0.0",
    "gulp-flatten": "0.0.4",
    "gulp-if": "^1.2.1",
    "gulp-imagemin": "^2.0.0",
    "gulp-jshint": "^1.6.3",
    "gulp-load-plugins": "^0.8.0",
    "gulp-minify-html": "0.1.5",
    "gulp-replace": "^0.5.0",
    "gulp-sass": "^1.2.0",
    "gulp-size": "^1.0.0",
    "gulp-sourcemaps": "^1.3.0",
    "gulp-uglify": "^1.0.1",
    "gulp-uncss": "^1.0.0",
    "gulp-useref": "^1.0.1",
    "jshint-stylish": "^1.0.0",
    "opn": "^1.0.0",
    "psi": "^1.0.4",
    "require-dir": "^0.1.0",
    "run-sequence": "^1.0.1"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "private": true,
  "scripts": {
    "test": "gulp && git status | grep 'working directory clean' >/dev/null || (echo 'Please commit all changes generated by building'; exit 1)"
  }
} 
```

###Installing & Rebuilding Node-Sass###

Rebuilding node-sass seems to generate the same error as before:
*$ npm rebuild node-sass* 

```console
> node-sass@2.1.1 install /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass
> node scripts/install.js


> node-sass@2.1.1 postinstall /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass
> node scripts/build.js

gyp: /Users/oxymoron/.node-gyp/4.2.1/common.gypi not found (cwd: /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/Cellar/node/4.2.1/bin/node" "/Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp" "rebuild"
gyp ERR! cwd /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v4.2.1
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
Build failed
node-sass@2.1.1 /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/gulp-sass/node_modules/node-sass
```

When I try installing node-sass it indicates that they're nothing wrong with my install.
*$ npm install node-sass*

```console
> spawn-sync@1.0.13 postinstall /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/node-sass/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

/
> node-sass@3.3.3 install /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/node-sass/vendor/darwin-x64-46/binding.node

> node-sass@3.3.3 postinstall /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/node-sass
> node scripts/build.js

` /Applications/AMPPS/www/repos/demos/web-starter-kit-0.5.4/node_modules/node-sass/vendor/darwin-x64-46/binding.node ` exists. 
 testing binary.
Binary is fine; exiting.
node-sass@3.3.3 node_modules/node-sass
├── get-stdin@4.0.1
├── async-foreach@0.1.3
├── nan@2.1.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── npmconf@2.1.2 (ini@1.3.4, uid-number@0.0.5, inherits@2.0.1, once@1.3.2, semver@4.3.6, osenv@0.1.3, config-chain@1.1.9, nopt@3.0.4)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@3.0.0)
├── gaze@0.5.2 (globule@0.1.0)
├── cross-spawn@2.0.0 (cross-spawn-async@2.0.0, spawn-sync@1.0.13)
├── meow@3.4.2 (loud-rejection@1.0.0, trim-newlines@1.0.0, object-assign@4.0.1, minimist@1.2.0, camelcase-keys@1.0.0, redent@1.0.0, read-pkg-up@1.0.1, normalize-package-data@2.3.4)
├── node-gyp@3.0.3 (graceful-fs@4.1.2, semver@5.0.3, osenv@0.1.3, nopt@3.0.4, minimatch@1.0.0, fstream@1.0.8, which@1.2.0, glob@4.5.3, tar@1.0.3, rimraf@2.4.3, path-array@1.0.0, npmlog@1.2.1)
├── request@2.65.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.1, oauth-sign@0.8.0, caseless@0.11.0, stringstream@0.0.4, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.0, node-uuid@1.4.3, qs@5.2.0, form-data@1.0.0-rc3, combined-stream@1.0.5, mime-types@2.1.7, http-signature@0.11.0, hawk@3.1.0, bl@1.0.0, har-validator@2.0.2)
└── sass-graph@2.0.1 (lodash@3.10.1, yargs@3.27.0)
```

Is there something I'm missing or need to try? Again, thanks in advance!!

**Comment by lodestarops** [comment]
For reference, It looks like this issue is being addressed here #756

The long and short of it is there's a release candidate that address this issue (v0.6.0-rc1). 
https://github.com/google/web-starter-kit/releases/tag/v0.6.0-rc.1

Hopefully there will be official release soon. =)
