### ISSUE TITLE
fsevents doesn't install on linux

### ISSUE THREAD

**Issue by garyterry** [google/web-starter-kit#796]
Hi Guys, I have got the WSK and MDL working on my windows machine at work. Some minor things seem to not work (touch images not copied on gulp serve:dist) but it's most likely permission issues. Anyhow while trying to get wsk-0.6.0 working in Linux Mint 17.3 I've come across this:

 ~/dev.server/wsk-0.6.0 $ sudo npm install
/home/dev.server/wsk-0.6.0
└── lodash@3.10.1 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

Which seems to be important... because it won't build as a result.
I keep getting this error when I run gulp serve:dist (it doesn't serve properly any other way either):

 ~/dev.server/wsk-0.6.0 $ gulp serve:dist
[13:57:31] Requiring external module babel-core/register
/home/dev.server/wsk-0.6.0/gulpfile.babel.js:28
import fs from 'fs';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at loader (/home/dev.server/wsk-0.6.0/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/dev.server/wsk-0.6.0/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)

I've tried uninstalling and reinstalling twice now... same error every time. Any suggestions? Thanks in advance...

**Comment by rabbit210** [comment]
@garyterry Have the same issue. Did found any workaround?

**Comment by lduboeuf** [comment]
same here 
`Linux xxxx 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by borivojevic** [comment]
@garyterry I don't see how your problem is related to fsevents. Make sure you have `.babelrc` file in the same directory as `gulpfile.babel.js` though.

**Comment by devtip** [comment]
@garyterry @rabbit210 As @borivojevic said, just make sure .babelrc file in the same directory as gulpfile.babel.js though.You should create a .babelrc file and paste this WSK .babelrc code[https://github.com/google/web-starter-kit/blob/master/.babelrc]. 
Now, my project is working! Enjoy :-(

**Comment by garyterry** [comment]
@borivojevic Those files are installed by the default installation... are they not? They are both present and correct. The fs events error now tells me my Linux OS isn't supported. Is this true? Haven't solved this one yet...

**Comment by Florian-R** [comment]
Fsevents is an optional dependency of Chokidar, it's only necessary for OSX, so this is unrelated.

**Comment by felipecaputo** [comment]
Same error here in Ubuntu 15.10

```
$ npm i babel-loader --save
react-stack@1.0.0 /home/felipe/src/pluralSight/react-stack
├── UNMET PEER DEPENDENCY babel-core@^6.0.0
└─┬ babel-loader@6.2.4 
  └── object-assign@4.0.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.9
npm WARN babel-loader@6.2.4 requires a peer of babel-core@^6.0.0 but none was installed.
npm WARN react-stack@1.0.0 No description
npm WARN react-stack@1.0.0 No repository field.
```

**Comment by LestaD** [comment]
![image](https://cloud.githubusercontent.com/assets/5620073/14346072/370c009c-fcb9-11e5-81cc-b64e9df23819.png)

ubuntu 14.10

**Comment by maicWorkGithub** [comment]
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
`

**Comment by xWinGeD** [comment]
maicWorkGithub: I have the same issue. Could you please tell me how you solved it?

**Comment by maicWorkGithub** [comment]
@xWinGeD I didn't...still wait the author to solve this.

**Comment by PangastikaDian** [comment]
@LestaD i have same errors. could you please tell me how you solved it ?

**Comment by jingwang88** [comment]
![image](https://cloud.githubusercontent.com/assets/8048415/21072155/e9f4acf2-bef3-11e6-884f-8095c8a5fb5e.png) i have same errors!!

**Comment by mujahidinside** [comment]
![npm](https://cloud.githubusercontent.com/assets/10596346/21339240/5e9f075c-c69f-11e6-8f8c-512895659223.PNG)

when i install angular2

git clone https://github.com/angular/quickstart.git quickstart
cd quickstart
npm install
npm start

**Comment by aadshalshihry** [comment]
I have same error here. I am using Linux Mint 18.

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15

**Comment by PEZ** [comment]
I get this when I npm install the CLI version of `postcss` with `autoprefixer`. It works on macos but not inside a Docker container.

**Comment by LestaD** [comment]
@xWinGeD i'm not solved this

**Comment by Garbee** [comment]
There is **nothing** to solve here. It is an **optional** dependency and is only needed in MacOS environments. Linux and Windows both provide native ways to do what this dependency is needed for on MacOS.

**Comment by odiumediae** [comment]
Is it possible to ignore this particular info somehow, if it can't be solved? I see no reason why Linux and Windows users should be pestered with this annoying message on every package installation. Quite frankly, it's pretty annoying and unnecessary.

**Comment by Garbee** [comment]
I think `--no-optional` when installing will work, however that can have side-effects if other packages have optional deps that may be relied upon by accident. This is really something developers need to take up with Node so they can solve it better in NPM itself. The pestering is out of our control as this is caused by a package we depend upon needing the optional dependency.

**Comment by odiumediae** [comment]
Thank you, @Garbee. I'll try out `--no-optional`.

**Comment by hegdeas** [comment]
@odiumediae  Please share your findings. if you get a chance to try the above?

**Comment by odiumediae** [comment]
@hegdeas It does work, as long as the setup is not too complicated (optional deps can become a problem, just as @Garbee  mentioned), so it's not a suitable workaround, but the only one I know so far apart from ignoring the warning.

**Comment by michaelfig** [comment]
The screenshots have shown the WARN triggered by fsevents on Linux, but that's not the real problem.  A little while later when I'm running mvn package on my own plugin, it triggers an ERR! which halts the build.  Can anybody be more specific about the workaround?  When I'm doing a mvn package, where should I add --no-optional?

```
npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
npm ERR! argv "/home/michael/git/graylog-project/graylog-plugin-delta/node/node" "/home/michael/git/graylog-project/graylog-plugin-delta/node/node_modules/npm/bin/npm-cli.js" "install" "--no-optional"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64
```

**Comment by thanhngvpt** [comment]
Same problem, temporary solution for angular2 cli is `ng new <project> --skip-install` then run `yarn install`

**Comment by germansokolov13** [comment]
I wonder if this message about wrong architecture may be changed to less startle developers then. They see the message and think that something is wrong though it may be fine.

**Comment by Garbee** [comment]
@germansokolov13 That's an issue for node (NPM) to handle. This error is generated by the NPM install process of the package based on the package's requirements. There is nothing that we can do about it on WSK.

**Comment by BradGriffith** [comment]
This is a late reply, but I had success with:

```
rm -rf node_modules package-lock.json yarn.lock
yarn install --no-optional
```

Before removing the lock files, I kept getting the same error with the `--no-optional` flag.

**Comment by Little-Little-Monster** [comment]
surprise https://lupeier.com/post/linux-npm-install-eacces/

**Comment by allanist** [comment]
optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
npm WARN js-starter-code@1.0.0 No repository field.

**Comment by mcnaveen** [comment]
`rm -rf node_modules package-lock.json yarn.lock`

`yarn install --no-optional`

[Above commands helped me to fix it. Here is the Source](https://webcheerz.com/fix-fsevents-doesnt-install-on-linux/)
