### ISSUE TITLE
Windows installation fails due to missing VCBuild.exe

### ISSUE THREAD

**Issue by dandv** [google/web-starter-kit#821]
This is due to two npm libraries requiring node-gyp, which is a mess on Windows.

https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245

``` text
npm WARN prefer global node-gyp@3.2.1 should be installed with -g

> bufferutil@1.2.1 install C:\prg\web-starter-kit-0.6.1\node_modules\bufferutil
> node-gyp rebuild

C:\prg\web-starter-kit-0.6.1\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\prg\web-starter-kit-0.6.1\node_modules\bufferutil\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm
\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\prg\web-starter-kit-0.6.1\node_modules\bufferutil
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\prg\web-starter-kit-0.6.1\node_modules\utf-8-validate
> node-gyp rebuild
```

Same for `utf-8-validate`.

The prerequisites should probably mention [some flavor of MS Visual Studio](https://github.com/nodejs/node-gyp/issues/307#issuecomment-31004410), and Python.

I'm using node 5.5.0 on Windows 7 64 bit.

**Comment by lokeshreddy135** [comment]
I had the same issue on windows and resolved by following steps from [#link](https://github.com/nodejs/node-gyp)  installation steps.

**Comment by sindresorhus** [comment]
Is the install actually failing? Most native dependencies like these are usually optional and will not fail the install even though they fail compiling.

**Comment by gauntface** [comment]
Defines the `inline-css` task. This will minify inline CSS.

**Comment by gauntface** [comment]
🐛 **Bankruptcy**: Closing due to inactivity.
