### ISSUE TITLE
Error: Cannot find module './lib/log'

### ISSUE THREAD

**Issue by andrejohansson** [google/web-starter-kit#828]
I'm trying to build a clean clone of this kit on a Windows 10 machine.

```
joandre@joandre-w10 MINGW64 /c/Dev/github/web-starter-kit (master)
$ gulp
[15:03:38] Failed to load external module babel-register
[15:03:38] Requiring external module babel-core/register
[15:03:38] Warning: gulp version mismatch:
[15:03:38] Global gulp is 3.9.1
[15:03:38] Local gulp is 3.9.0
[15:03:43] Using gulpfile C:\Dev\github\web-starter-kit\gulpfile.babel.js
[15:03:43] Starting 'clean'...
[15:03:43] Finished 'clean' after 6.76 ms
[15:03:43] Starting 'default'...
[15:03:43] Starting 'styles'...
[15:03:43] 'styles' errored after 23 ms
[15:03:43] Error: Cannot find module './lib/log'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Dev\github\web-starter-kit\node_modules\gulp-newer\node_modules\gulp-util\index.js:6:8)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Dev\github\web-starter-kit\node_modules\babel-core\node_modules\babel-register\lib\node.js:138:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
[15:03:43] 'default' errored after 27 ms
[15:03:43] Error in plugin 'run-sequence'
Message:
    An error occured in task 'styles'.

joandre@joandre-w10 MINGW64 /c/Dev/github/web-starter-kit (master)
```

I have tried all variaions of `npm install ..` to get the dependencies in place with no luck. Looking if the missing file is there, it seems so:

```
c:\Dev\github\web-starter-kit\node_modules\gulp-util\lib>dir
 Volume in drive C has no label.
 Volume Serial Number is B898-A3D1

 Directory of c:\Dev\github\web-starter-kit\node_modules\gulp-util\lib

2016-02-10  15:07    <DIR>          .
2016-02-10  15:07    <DIR>          ..
2016-02-10  15:03               282 buffer.js
2016-02-10  15:03               240 combine.js
2016-02-10  15:03               106 env.js
2016-02-10  15:03               209 isBuffer.js
2016-02-10  15:03                55 isNull.js
2016-02-10  15:03               111 isStream.js
2016-02-10  15:03               430 log.js
2016-02-10  15:03                94 noop.js
2016-02-10  15:03             3 795 PluginError.js
2016-02-10  15:03               636 template.js
2016-02-10  15:07               259 tree.txt
              11 File(s)          6 217 bytes
               2 Dir(s)  527 304 007 680 bytes free
```

Any ideas why the log lib can´t be found?

**Comment by andrejohansson** [comment]
Resolved, this was due to a faulty installation. I had Python 3 installed, but the toolchain for WSK seems to require python 2.7. 

I fixed it with the following steps:
* Clean cache and remove node_modules folder
* Install python 2.7
* Restart the console to pick up paths
* Reinstall with `npm install`
* Rebuild using `gulp`
