### ISSUE TITLE
Failed to load external module babel/register

### ISSUE THREAD

**Issue by enavarrocu** [google/web-starter-kit#862]
gulp serve                   
[02:03:42] Failed to load external module babel/register
/Test/web-starter-kit/gulpfile.babel.js:27
import path from 'path';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)

**Comment by parialegend** [comment]
i am still having this issue. how did you get it working?
