### ISSUE TITLE
Error: Cannot find module 'eslint-plugin-react'

### ISSUE THREAD

**Issue by leibovic** [google/web-starter-kit#870]
With a fresh install, running `gulp` gives me the following error. I'm running node v.6.2.1 and gulp 3.9.1.

```
[leibovic@margaret-mbp:~/code/wiki-near-me]$ gulp
[10:11:00] Requiring external module babel-register
[10:11:01] Using gulpfile ~/code/wiki-near-me/gulpfile.babel.js
[10:11:01] Starting 'clean'...
[10:11:01] Finished 'clean' after 4.94 ms
[10:11:01] Starting 'default'...
[10:11:01] Starting 'styles'...
[10:11:03] styles all files 3 kB
[10:11:03] Finished 'styles' after 1.51 s
[10:11:03] Starting 'lint'...
[10:11:03] Starting 'html'...
[10:11:03] Starting 'scripts'...
[10:11:03] Starting 'images'...
[10:11:03] Starting 'copy'...
module.js:341
    throw err;
    ^

Error: Cannot find module 'eslint-plugin-react'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /Users/leibovic/code/wiki-near-me/node_modules/eslint/lib/cli-engine.js:125:26
    at Array.forEach (native)
    at loadPlugins (/Users/leibovic/code/wiki-near-me/node_modules/eslint/lib/cli-engine.js:116:21)
    at processText (/Users/leibovic/code/wiki-near-me/node_modules/eslint/lib/cli-engine.js:204:5)
    at CLIEngine.executeOnText (/Users/leibovic/code/wiki-near-me/node_modules/eslint/lib/cli-engine.js:686:26)
    at verify (/Users/leibovic/code/wiki-near-me/node_modules/gulp-eslint/index.js:20:23)
    at Transform._transform (/Users/leibovic/code/wiki-near-me/node_modules/gulp-eslint/index.js:68:18)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Transform.Writable.write (_stream_writable.js:215:11)
    at write (/Users/leibovic/code/wiki-near-me/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/leibovic/code/wiki-near-me/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/leibovic/code/wiki-near-me/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at emitReadable_ (/Users/leibovic/code/wiki-near-me/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
```

**Comment by leibovic** [comment]
After running `npm install eslint-plugin-react`, this error goes away, but I run into another issue:

```
[leibovic@margaret-mbp:~/code/wiki-near-me]$ gulp
[10:22:39] Requiring external module babel-register
(node:68287) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[10:22:40] Using gulpfile ~/code/wiki-near-me/gulpfile.babel.js
[10:22:40] Starting 'clean'...
[10:22:40] Finished 'clean' after 11 ms
[10:22:40] Starting 'default'...
[10:22:40] Starting 'styles'...
[10:22:41] styles all files 3 kB
[10:22:41] Finished 'styles' after 1.71 s
[10:22:41] Starting 'lint'...
[10:22:41] Starting 'html'...
[10:22:42] Starting 'scripts'...
[10:22:42] Starting 'images'...
[10:22:42] Starting 'copy'...
[10:22:42] 'lint' errored after 541 ms
[10:22:42] ESLintError in plugin 'gulp-eslint'
Message:
    Definition for rule 'react/jsx-quotes' was not found
Details:
    fileName: app/scripts/main.js
    lineNumber: 20
[10:22:42] 'default' errored after 2.25 s
[10:22:42] Error in plugin 'run-sequence(lint)'
Message:
    lint stream
[10:22:42] html basic.html 1.32 kB
[10:22:42] 
app/scripts/main.js
  20:1  error  Definition for rule 'react/jsx-quotes' was not found  react/jsx-quotes

app/scripts/sw/runtime-caching.js
  24:1  error  Definition for rule 'react/jsx-quotes' was not found  react/jsx-quotes

✖ 2 problems (2 errors, 0 warnings)

[10:22:42] html index.html 14.98 kB
[10:22:42] html all files 16.3 kB
[10:22:42] scripts all files 1.32 kB
[10:22:42] Finished 'html' after 587 ms
[10:22:42] Finished 'scripts' after 486 ms
[10:22:42] images all files 7.39 kB
[10:22:42] Finished 'images' after 481 ms
[10:22:42] copy all files 45.8 kB
[10:22:42] Finished 'copy' after 368 ms
```

**Comment by addyosmani** [comment]
This was an issue with an upstream dependency at one point but should be resolved with eslint itself. Can you try `npm install --save-dev eslint eslint-plugin-react` against WSK and see if that fixes things?

**Comment by leibovic** [comment]
This works fine with a fresh install of web-starter-kit 0.6.4. Thanks for taking a look!
