### ISSUE TITLE
Babel Core ^6.0.0 - Unexpected token import

### ISSUE THREAD

**Issue by mantovanig** [google/web-starter-kit#882]
With new major version of Babel Core the gulpfile.babel.js return this error:

> /Users/mantovanig/Documents/lab/pwa_test/gulpfile.babel.js:27
> import path from 'path';
> ^^^^^^
> SyntaxError: Unexpected token import
>     at Object.exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:513:28)
>     at loader (/Users/mantovanig/Documents/lab/pwa_test/node_modules/babel-register/lib/node.js:148:5)
>     at Object.require.extensions.(anonymous function) [as .js](/Users/mantovanig/Documents/lab/pwa_test/node_modules/babel-register/lib/node.js:158:7)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)

To fix this read [this issue on gulp](https://github.com/gulpjs/gulp/issues/1364).

**Comment by dmitrika** [comment]
Faced the same problem.

Added in WSK root dir .babelrc with:

```
{
  "presets": ["es2015"]
}
```

and babel-preset-es2015 as dev-dep.

Is that a right move, to add this to the origin repo?

**Comment by gauntface** [comment]
🐛 **Bankruptcy**: Closing due to inactivity.
