### ISSUE TITLE
There is a error when running gulp command

### ISSUE THREAD

**Issue by JacobWay** [google/web-starter-kit#902]
$ sudo gulp
[16:57:35] Requiring external module babel-register
[16:57:36] Using gulpfile ~/Projects/Front_End_Web/web-starter-kit/gulpfile.babel.js
[16:57:36] Starting 'clean'...
[16:57:36] Finished 'clean' after 6.97 ms
[16:57:36] Starting 'default'...
[16:57:36] Starting 'styles'...
[16:57:37] styles all files 3.81 kB
[16:57:37] Finished 'styles' after 892 ms
[16:57:37] Starting 'lint'...
[16:57:37] Starting 'html'...
[16:57:37] Starting 'scripts'...
[16:57:37] Starting 'images'...
[16:57:38] Starting 'copy'...
(node:68408) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[16:57:38] html basic.html 1.32 kB
[16:57:38] Finished 'lint' after 921 ms
[16:57:38] html index.html 14.94 kB
[16:57:38] html all files 16.25 kB
[16:57:38] scripts all files 1.32 kB
_**Unhandled rejection Error: spawn /Users/jacobway/Projects/Front_End_Web/web-starter-kit/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)**_

[16:57:38] Finished 'html' after 863 ms
[16:57:38] Finished 'scripts' after 678 ms
[16:57:38] copy all files 45.8 kB
[16:57:38] Finished 'copy' after 471 ms

**Comment by akshaysinghi** [comment]
The reason for the error is there is a limit in the system for how many files can be watched by a user, using the following command in a terminal window we can simply increase the limit .echo **fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p** 

if this not work

**fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf | sudo sysctl -p**
