### ISSUE TITLE
Cannot find module 'gulp-load-plugins'

### ISSUE THREAD

**Issue by prakashdge** [google/web-starter-kit#912]
I ran following commands in my local
1. npm install --global gulp
2. npm install
3. gulp

then getting the following error.

Error: Cannot find module 'gulp-load-plugins'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by prakashdge** [comment]
npm clear cache worked, I have cleared cache and rerun the above commands worked for me
