### ISSUE TITLE
Error: pass strings or arrays of strings

### ISSUE THREAD

**Issue by maartenflippo** [google/web-starter-kit#920]
When trying to run `gulp`, it gives me the following crash:
```bash
Error: pass strings or arrays of strings
    at Gulp.Orchestrator.start (C:\Users\s163249\Documents\Development\Sites\webux\node_modules\orchestrator\index.js:89:12)
    at runNextSet (C:\Users\s163249\Documents\Development\Sites\webux\node_modules\run-sequence\index.js:86:16)
    at Gulp.onTaskEnd (C:\Users\s163249\Documents\Development\Sites\webux\node_modules\run-sequence\index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\s163249\Documents\Development\Sites\webux\node_modules\orchestrator\index.js:264:8)
    at C:\Users\s163249\Documents\Development\Sites\webux\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\s163249\Documents\Development\Sites\webux\node_modules\orchestrator\lib\runTask.js:21:8)
    at C:\Users\s163249\Documents\Development\Sites\webux\node_modules\orchestrator\lib\runTask.js:52:4
    at f (C:\Users\s163249\Documents\Development\Sites\webux\node_modules\end-of-stream\node_modules\once\once.js:17:25)
```

This crash also periodically happens when `gulp serve` is used, and always happens when `gulp serve:dist` is used (probably because `serve:dist` runs the default task). I have tried to find the cause but failed. Any help is appreciated.

**Comment by cristianounix** [comment]
I can not reproduce this error, can you write more details about it ?
